### ISSUE TITLE
Crash when viewing EML that contains whitespace in URL or directory attr

### ISSUE THREAD

**Issue by rogerdahl** [PASTAplus/DataPortal#105]

**Comment by servilla** [comment]
This issue needs more information, please!

**Comment by rogerdahl** [comment]
commit 9bab5fa1e8fbd2ab1a16f532cbaf544d44e217f1
Author: rogerdahl <git@dahlsys.com>
Date:   Wed Nov 1 19:19:40 2023 -0600

    Hotfix: Crash when viewing EML that contains whitespace in URL or directory attr #105
