### ISSUE TITLE
Journal Citation: Journal citation creation workflow does not retain data package information when a user must log in

### ISSUE THREAD

**Issue by servilla** [PASTAplus/DataPortal#142]
On Mon, Jul 29, 2024 at 9:11 AM a data portal user wrote:

>  On a dataset landing page, when I click Add Journal Citation, if I am not already logged in, I am prompted to log in. Then I click New Citation. Then it asks me for the package ID. But I can no longer see the package ID on the page I was at. If the site can't remember and auto-populate the package ID I was at when I clicked Add Journal Citation, perhaps when one clicks Add Journal Citation it should open in a new tab.

**Comment by twhiteaker** [comment]
Note if I'm logged in beforehand, things work great.
