### ISSUE TITLE
Update XSLT Logic to Display All EML Annotations as Hyperlinks in the Data Portal

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/DataPortal#148]
## Description

@twhiteaker reported an issue (thanks Tim!) with the display of attribute annotations in the EDI Data Portal. Currently, only annotations from the [Ecosystem Ontology](https://bioportal.bioontology.org/ontologies/ECSO) (ECSO) are hyperlinked to their respective URIs, while annotations from other ontologies (e.g., [QUDT](https://qudt.org/)) are not. This inconsistency prevents users from easily accessing more information about non-ECSO annotations. The expected behavior is that all annotation labels should be hyperlinked to their respective URIs, regardless of the ontology.

## Root Cause
The issue arises from an XSLT condition that checks if the URI contains the string 'purl' (see [here](https://github.com/PASTAplus/DataPortal/blob/277f8230d939d4a30268d3ca9b311576b2f8f074/WebRoot/WEB-INF/xsl/eml-2.xsl#L11493C9-L11504C20)). If it does, the annotation label is hyperlinked; if not, the hyperlink is omitted. This logic was initially implemented to ensure the legitimacy of URIs.

## Proposed Solution
Since not all valid URIs contain 'purl', we recommend removing this condition. Instead, any validity checks for URIs should be handled by EDI’s EML Congruence Checker, allowing users to correct any invalid URIs before submitting their metadata.

## Recommended Action
For now, the Data Portal's detailed metadata pages should always hyperlink the property and value labels with the `propertyURI` and `valueURI` of an EML annotation element, regardless of the URI's "validity". This ensures all annotations are treated equally while maintaining flexibility for future enhancements.

**Comment by twhiteaker** [comment]
Solution sounds good!

**Comment by servilla** [comment]
Both URIs for the value and property elements of annotations are now hyperlinked.

**Comment by twhiteaker** [comment]
Marvelous. Thanks!

**Comment by clnsmth** [comment]
@servilla can we close out this issue?
