### ISSUE TITLE
Support rendering of LaTex in text fields

### ISSUE THREAD

**Issue by servilla** [PASTAplus/DataPortal#47]
The full metadata display rendering (including the preview) should render LaTex equations. This is possible through a 3rd party JavaScript application called MathJax:

`<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>`

**Comment by mobb** [comment]
So sorry. While looking at another problem, I ran into this warning about mathjax: 

MathJax.js?config=TeX-MML-AM_CHTML:32 WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.

message appeared in Chrome developer tools, while I was looking at a doc using the previewer (https://portal.edirepository.org/nis/metadataPreviewer)
