### ISSUE TITLE
add links to  the data portal for how to submit data - 3 places.

### ISSUE THREAD

**Issue by mobb** [PASTAplus/DataPortal#67]
First, on the portal entry page:  https://portal.edirepository.org/nis/home.jsp
needs a link to tell people how to submit data, so to this page:
https://environmentaldatainitiative.org/submit-your-data/

Suggestion: 
above the 2 paragraphs, add this link as an `<h2>`. Center it above the paragraphs.
e.g, 

`<h2><a href="https://environmentaldatainitiative.org/submit-your-data/">Submit Data</a></h2>`

**Comment by mobb** [comment]
Also, on the main Help menu,
add a link "How to Submit Data", with a link to https://environmentaldatainitiative.org/submit-your-data/

**Comment by mobb** [comment]
On this page:
https://portal.edirepository.org/nis/resources.jsp

under EDI Reseources
a link to "Submit Data", that goes to  https://environmentaldatainitiative.org/submit-your-data/

**Comment by servilla** [comment]
Will the text "Submit Data" confuse those who already go to the upload page of the Data Portal? Would it be better to have something like "How to Submit Data"?

**Comment by cgries** [comment]
"How to Submit Data" is fine too.
