### ISSUE TITLE
Add publication date and author list to the journal citation table

### ISSUE THREAD

**Issue by servilla** [PASTAplus/DataPortal#97]
Add entries for publication date (year) and author list to the Journal Citation table view. Add the publication date and author list to items that are generated from the Crossref citation request.

**Comment by rogerdahl** [comment]
Note from Mary:

I use the following command to get full nicely formatted citations from crossref. It will also output bibtex, json and a gazillion other citation styles.
-Mary

curl -LH "Accept: text/bibliography; style=apa" https://doi.org/10.1016/j.soilbio.2016.12.028 | pandoc -f plain -t html -s -o citation.html

Durán, J., Morse, J. L., Rodríguez, A., Campbell, J. L., Christenson, L. M., Driscoll, C. T., Fahey, T. J., Fisk, M. C., Mitchell, M. J., Templer, P. H., & Groffman, P. M. (2017).Diff erential sensitivity to climate change of C and N cycling processes across soil horizons in a northern hardwood forest. Soil Biology and Biochemistry, 107, 77–84. https://doi.o/rg/10.1016/j.soilbio.2016.12.028
